<?php
/**
 * IntegrationApiModelsNextActionType
 *
 * PHP version 5
 *
 * @category Class
 * @package  Openpay\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Integration API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.22
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Openpay\Client\Model;
use \Openpay\Client\ObjectSerializer;

/**
 * IntegrationApiModelsNextActionType Class Doc Comment
 *
 * @category Class
 * @description The next action to take in the flow. Depending on the type, it may be accompanied by a matching object with details.
 * @package  Openpay\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class IntegrationApiModelsNextActionType
{
    /**
     * Possible values of this enum
     */
    const FORM_POST = 'FormPost';
const WAIT_FOR_CUSTOMER = 'WaitForCustomer';
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::FORM_POST,
self::WAIT_FOR_CUSTOMER,        ];
    }
}
