<?php
/**
 * Template file to display payment form for openpay.
 * 
 * @category Openpay
 * @package  Openpay_Payment
 * @author   ideatarmac.com
 */
?>

<?php
$openpay_helper = Mage::helper('openpay_payment');
$_code = $this->getMethodCode();
?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
    <div> 
        <?php echo $openpay_helper->getPaymentMethodDescription();?>
        <script> 
            if (!window.isOpenpayJsLoaded) {
                var element = document.createElement("input");
                element.type = "hidden";
                element.value = "1";
                element.name = "openpayJsLoaded";
                document.getElementById("payment_form_<?php echo $_code ?>").appendChild(element);
            }
        </script>
    </div>
</ul>
